CREATE TABLE "game0_gift" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game0_gift_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"imageUrl" text,
	"coinCost" integer NOT NULL,
	"vendor" varchar(64) DEFAULT 'amazon' NOT NULL,
	"voucherAmount" integer,
	"active" integer DEFAULT 1 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "game0_purchase" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game0_purchase_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"giftId" integer NOT NULL,
	"redemptionCode" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "game0_wallet_txn" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game0_wallet_txn_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"amount" integer NOT NULL,
	"type" varchar(20) NOT NULL,
	"reason" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "game0_wallet" (
	"userId" varchar(255) PRIMARY KEY NOT NULL,
	"balance" integer DEFAULT 0 NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
ALTER TABLE "game0_purchase" ADD CONSTRAINT "game0_purchase_userId_game0_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."game0_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game0_purchase" ADD CONSTRAINT "game0_purchase_giftId_game0_gift_id_fk" FOREIGN KEY ("giftId") REFERENCES "public"."game0_gift"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game0_wallet_txn" ADD CONSTRAINT "game0_wallet_txn_userId_game0_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."game0_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game0_wallet" ADD CONSTRAINT "game0_wallet_userId_game0_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."game0_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "gift_active_idx" ON "game0_gift" USING btree ("active");--> statement-breakpoint
CREATE INDEX "purchase_user_id_idx" ON "game0_purchase" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "purchase_gift_id_idx" ON "game0_purchase" USING btree ("giftId");--> statement-breakpoint
CREATE INDEX "wallet_txn_user_id_idx" ON "game0_wallet_txn" USING btree ("userId");