CREATE TABLE "game0_coin_package" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game0_coin_package_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"currency" varchar(8) NOT NULL,
	"coins" integer NOT NULL,
	"amountMinor" integer NOT NULL,
	"active" integer DEFAULT 1 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX "coin_pkg_currency_idx" ON "game0_coin_package" USING btree ("currency");--> statement-breakpoint
CREATE INDEX "coin_pkg_active_idx" ON "game0_coin_package" USING btree ("active");