CREATE TABLE "game0_prize_variant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game0_prize_variant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"prizeId" integer NOT NULL,
	"label" varchar(255) NOT NULL,
	"coinCost" integer NOT NULL,
	"sku" varchar(64),
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"active" integer DEFAULT 1 NOT NULL,
	"fulfillmentType" varchar(64),
	"fulfillmentConfig" jsonb,
	"metadata" jsonb,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "game0_prize" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game0_prize_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"description" text,
	"imageUrl" text,
	"videoUrl" text,
	"vendor" varchar(64) DEFAULT 'generic',
	"active" integer DEFAULT 1 NOT NULL,
	"metadata" jsonb,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
ALTER TABLE "game0_purchase" ADD COLUMN "prizeVariantId" integer;--> statement-breakpoint
ALTER TABLE "game0_prize_variant" ADD CONSTRAINT "game0_prize_variant_prizeId_game0_prize_id_fk" FOREIGN KEY ("prizeId") REFERENCES "public"."game0_prize"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "prize_variant_prize_id_idx" ON "game0_prize_variant" USING btree ("prizeId");--> statement-breakpoint
CREATE INDEX "prize_variant_active_idx" ON "game0_prize_variant" USING btree ("active");--> statement-breakpoint
CREATE INDEX "prize_variant_sort_idx" ON "game0_prize_variant" USING btree ("sortOrder");--> statement-breakpoint
CREATE INDEX "prize_active_idx" ON "game0_prize" USING btree ("active");--> statement-breakpoint
ALTER TABLE "game0_purchase" ADD CONSTRAINT "game0_purchase_prizeVariantId_game0_prize_variant_id_fk" FOREIGN KEY ("prizeVariantId") REFERENCES "public"."game0_prize_variant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "purchase_variant_id_idx" ON "game0_purchase" USING btree ("prizeVariantId");