CREATE TABLE "game0_prize_comment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game0_prize_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"prizeId" integer NOT NULL,
	"text" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "game0_prize_want" (
	"userId" varchar(255) NOT NULL,
	"prizeId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "game0_prize_want_userId_prizeId_pk" PRIMARY KEY("userId","prizeId")
);
--> statement-breakpoint
ALTER TABLE "game0_purchase" ALTER COLUMN "giftId" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "game0_prize_variant" ADD COLUMN "buttonLabel" varchar(64);--> statement-breakpoint
ALTER TABLE "game0_prize" ADD COLUMN "vendorLogo" text;--> statement-breakpoint
ALTER TABLE "game0_prize_comment" ADD CONSTRAINT "game0_prize_comment_userId_game0_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."game0_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game0_prize_comment" ADD CONSTRAINT "game0_prize_comment_prizeId_game0_prize_id_fk" FOREIGN KEY ("prizeId") REFERENCES "public"."game0_prize"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game0_prize_want" ADD CONSTRAINT "game0_prize_want_userId_game0_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."game0_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game0_prize_want" ADD CONSTRAINT "game0_prize_want_prizeId_game0_prize_id_fk" FOREIGN KEY ("prizeId") REFERENCES "public"."game0_prize"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "prize_comment_prize_idx" ON "game0_prize_comment" USING btree ("prizeId");--> statement-breakpoint
CREATE INDEX "prize_want_prize_idx" ON "game0_prize_want" USING btree ("prizeId");