CREATE TABLE "game0_button_click" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game0_button_click_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event" varchar(128) NOT NULL,
	"source" varchar(64),
	"userId" varchar(255),
	"country" varchar(8),
	"region" varchar(128),
	"city" varchar(128),
	"timezone" varchar(64),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "game0_button_click" ADD CONSTRAINT "game0_button_click_userId_game0_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."game0_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "button_click_event_created_at_idx" ON "game0_button_click" USING btree ("event","createdAt");--> statement-breakpoint
CREATE INDEX "button_click_created_at_idx" ON "game0_button_click" USING btree ("createdAt");